import type { Product } from "./Products";

export const products: Product[] = [
  {
    id: 1,
    name: 'Headphones',
    href: '#',
    imageSrc: '/src/assets/ChatGPT Image 25 de mai. de 2025, 12_01_17.png',
    imageAlt: 'Dark green wireless over-ear headphones.',
    price: 299,
    color: 'Dark Green',
    rating: 5,
    reviewCount: 32,
    sizes: [
      { name: 'Standard', inStock: true },
    ],
  },
  {
    id: 2,
    name: 'Smartwatch',
    href: '#',
    imageSrc: '/src/assets/ChatGPT Image 25 de mai. de 2025, 12_04_59.png',
    imageAlt: 'Dark green smartwatch with fabric strap.',
    price: 199,
    color: 'Dark Green',
    rating: 4,
    reviewCount: 18,
    sizes: [
      { name: 'Standard', inStock: true },
    ],
  },
  {
    id: 3,
    name: 'Portable Speaker Model 1',
    href: '#',
    imageSrc: '/src/assets/ChatGPT Image 25 de mai. de 2025, 12_05_02.png',
    imageAlt: 'Dark green portable Bluetooth speaker with handle.',
    price: 149,
    color: 'Dark Green',
    rating: 4,
    reviewCount: 21,
    sizes: [
      { name: 'Standard', inStock: true },
    ],
  },
  {
    id: 4,
    name: 'Portable Speaker Model 2',
    href: '#',
    imageSrc: '/src/assets/ChatGPT Image 25 de mai. de 2025, 12_05_04.png',
    imageAlt: 'Dark green vertical portable speaker with fabric loop.',
    price: 159,
    color: 'Dark Green',
    rating: 5,
    reviewCount: 24,
    sizes: [
      { name: 'Standard', inStock: true },
    ],
  },
  {
    id: 5,
    name: 'Smartphone',
    href: '#',
    imageSrc: '/src/assets/ChatGPT Image 25 de mai. de 2025, 12_05_06.png',
    imageAlt: 'Dark green smartphone front view.',
    price: 899,
    color: 'Dark Green',
    rating: 5,
    reviewCount: 48,
    sizes: [
      { name: '128GB', inStock: true },
      { name: '256GB', inStock: true },
      { name: '512GB', inStock: false },
    ],
  },
  {
    id: 6,
    name: 'Portable Speaker Model 3',
    href: '#',
    imageSrc: '/src/assets/ChatGPT Image 25 de mai. de 2025, 12_05_08.png',
    imageAlt: 'Dark green compact portable speaker with buttons and loop.',
    price: 129,
    color: 'Dark Green',
    rating: 4,
    reviewCount: 15,
    sizes: [
      { name: 'Standard', inStock: true },
    ],
  },
  {
    id: 7,
    name: 'Portable Speaker Model 4',
    href: '#',
    imageSrc: '/src/assets/ChatGPT Image 25 de mai. de 2025, 12_05_11.png',
    imageAlt: 'Dark green portable speaker with rounded handle.',
    price: 179,
    color: 'Dark Green',
    rating: 4,
    reviewCount: 17,
    sizes: [
      { name: 'Standard', inStock: true },
    ],
  },
  {
    id: 8,
    name: 'Portable Speaker Model 5',
    href: '#',
    imageSrc: '/src/assets/ChatGPT Image 25 de mai. de 2025, 12_04_59.png',
    imageAlt: 'Dark green portable speaker with fabric mesh and side buttons.',
    price: 189,
    color: 'Dark Green',
    rating: 5,
    reviewCount: 22,
    sizes: [
      { name: 'Standard', inStock: true },
    ],
  },
];
