import type { Product } from "./Products";

export const products: Product[] = [
  {
    id: 1,
    name: 'Basic Tee',
    href: '#',
    imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-01.jpg',
    imageAlt: "Front of men's Basic Tee in black.",
    price: 35,
    color: 'Black',
    rating: 4,
    reviewCount: 12,
    sizes: [
      { name: 'P', inStock: true },
      { name: 'M', inStock: true },
      { name: 'G', inStock: false },
    ],
  },
  {
    id: 2,
    name: 'Cap',
    href: '#',
    imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-02.jpg',
    imageAlt: "Cap image.",
    price: 25,
    color: 'Blue',
    rating: 5,
    reviewCount: 8,
    sizes: [
      { name: 'P', inStock: true },
      { name: 'M', inStock: false },
      { name: 'G', inStock: true },
    ],
  },
  {
    id: 3,
    name: 'Shoes',
    href: '#',
    imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-03.jpg',
    imageAlt: "Shoes image.",
    price: 100,
    color: 'White',
    rating: 3,
    reviewCount: 5,
    sizes: [
      { name: 'P', inStock: false },
      { name: 'M', inStock: true },
      { name: 'G', inStock: true },
    ],
  },
  {
    id: 4,
    name: 'Hoodie',
    href: '#',
    imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-04.jpg',
    imageAlt: "Front of men's Hoodie in gray.",
    price: 60,
    color: 'Gray',
    rating: 4,
    reviewCount: 10,
    sizes: [
      { name: 'P', inStock: true },
      { name: 'M', inStock: true },
      { name: 'G', inStock: true },
    ],
  },
  {
    id: 5,
    name: 'Socks',
    href: '#',
    imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-05.jpg',
    imageAlt: "Pair of socks.",
    price: 10,
    color: 'White',
    rating: 5,
    reviewCount: 20,
    sizes: [
      { name: 'P', inStock: true },
      { name: 'M', inStock: true },
      { name: 'G', inStock: true },
    ],
  },
  {
    id: 6,
    name: 'Jacket',
    href: '#',
    imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-06.jpg',
    imageAlt: "Front of men's Jacket in navy.",
    price: 120,
    color: 'Navy',
    rating: 4,
    reviewCount: 7,
    sizes: [
      { name: 'P', inStock: false },
      { name: 'M', inStock: true },
      { name: 'G', inStock: true },
    ],
  },
  {
    id: 7,
    name: 'Backpack',
    href: '#',
    imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-07.jpg',
    imageAlt: "Backpack image.",
    price: 80,
    color: 'Black',
    rating: 5,
    reviewCount: 15,
    sizes: [
      { name: 'P', inStock: true },
      { name: 'M', inStock: true },
      { name: 'G', inStock: false },
    ],
  },
  {
    id: 8,
    name: 'Belt',
    href: '#',
    imageSrc: 'https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-08.jpg',
    imageAlt: "Leather belt image.",
    price: 20,
    color: 'Brown',
    rating: 3,
    reviewCount: 3,
    sizes: [
      { name: 'P', inStock: true },
      { name: 'M', inStock: false },
      { name: 'G', inStock: true },
    ],
  },
];
